language: java
sudo: false
before_install:
 - chmod +x gradlew
 - chmod +x gradle/wrapper/gradle-wrapper.jar
install: true

addons:
  sonarcloud:
    organization: "toberkoe-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk9

script:
  - ./gradlew clean test jacocoJUnit5TestReport sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'